DASDEC add/Ateme Titan Edge additions
SkylineCommunications/dataminer-docs-connectors pull request #327
Opened 2024-06-07 16:44 UTC by alexjohnson1993

2024-06-10 12:04 UTC, MariekeGO requested changes

2024-06-10 12:04 UTC, MariekeGO commented on connector/doc/Ateme_Titan_Edge.md
> +| 1.1.0.x   | API ??? Software v3.0.2|
Do you mean the API version is unknown?

2024-06-10 12:04 UTC, MariekeGO commented on connector/doc/DASDEC-III.md
> +# Digitial Alert Systems DASDEC-III
Could you confirm if "Digitial" is the correct spelling? Also, could you double-check whether the file name is correct? Usually, it is the same as the title of the page, except with underscores instead of spaces. Note that I also couldn't find an entry for DASDEC-III in the catalog.

2024-06-10 12:04 UTC, MariekeGO commented on connector/doc/DASDEC-III.md
> +- All other messages: Message will not be forwarded and be sent to **Alert Logging** table.
Do you mean that no message is forwarded or sent? The current phrasing is a bit ambiguous.

2024-06-10 12:04 UTC, MariekeGO commented on connector/doc/DASDEC-III.md
Could you add this new page to the toc.yml under the appropriate node?

2024-06-12 16:08 UTC, alexjohnson1993 commented on connector/doc/DASDEC-III.md
> +- All other messages: Message will not be forwarded and be sent to **Alert Logging** table.
Updated wording to be more clear

2024-06-12 16:08 UTC, alexjohnson1993 commented on connector/doc/DASDEC-III.md
> +# Digitial Alert Systems DASDEC-III
Fixed spelling/updated file name

2024-06-12 16:09 UTC, alexjohnson1993 commented on connector/doc/Ateme_Titan_Edge.md
> +| 1.1.0.x   | API ??? Software v3.0.2|
Yes API is unknown. Updated it to unknown.

2024-06-13 08:50 UTC, MariekeGO approved these changes

2024-06-13 08:59 UTC, MariekeGO requested changes
This PR has a merge conflict with the current main branch, because there range 1.1.0.x has also been added  to the Ateme Titan Edge pages. However, in the main branch, 1.1.0.x is indicated as the current main version, the key features description is different, and a firmware version is mentioned. Could you check which of the versions should be kept, yours or the currently published version?

2024-06-18 07:54 UTC, MariekeGO approved these changes

2024-06-18 07:55 UTC, merged