Update Skyline_Logical_Layer.md
SkylineCommunications/dataminer-docs-connectors pull request #364
Opened 2024-07-04 18:24 UTC by ConanVanHove

added more help info

2024-07-08 07:41 UTC, MariekeGO requested changes

2024-07-08 07:41 UTC, MariekeGO commented on connector/doc/Skyline_Logical_Layer.md
> +In this table, you can define monitors that can subscribe to a single parameter. This can be either a standalone parameter or a specific index of a table parameter.
In which table do you mean? Could you make sure this is clear?
This comment also applies for line 106 and 165.

2024-07-08 07:41 UTC, MariekeGO commented on connector/doc/Skyline_Logical_Layer.md
> +Explain Corrective Action Text - Automatic Correction - Corrective Action Script - Owner - Timestamp
What is the purpose of this text? could you clarify this?

2024-07-08 07:41 UTC, MariekeGO commented on connector/doc/Skyline_Logical_Layer.md
> +### Adding/Editing/Deleting Conditions
Info on editing/deleting conditions is still missing in this section. Could you add this?

2024-07-08 12:38 UTC, ConanVanHove commented on connector/doc/Skyline_Logical_Layer.md
> +In this table, you can define monitors that can subscribe to a single parameter. This can be either a standalone parameter or a specific index of a table parameter.
Yes, I will make this clear. I will review the whole document with this in mind and resolve any potential gaps.

2024-07-08 12:50 UTC, ConanVanHove commented on connector/doc/Skyline_Logical_Layer.md
> +### Adding/Editing/Deleting Conditions
Indeed, overlooked that one. Nice catch! Will add it.

2024-07-08 14:35 UTC, ConanVanHove commented on connector/doc/Skyline_Logical_Layer.md
> +In this table, you can define monitors that can subscribe to a single parameter. This can be either a standalone parameter or a specific index of a table parameter.
This should make it clear for line 56:
### Adding/Editing/Deleting a Parameter Monitor to/of/from the Parameter Value Monitors table

And this for line 106:
### Adding/Editing/Deleting Conditions to/of/from the Conditions table

Unclear for line 165 as I don't see any reference there to a table.

2024-07-09 06:24 UTC, MariekeGO approved these changes

2024-07-09 06:24 UTC, merged