Beckhoff KL3202
SkylineCommunications/dataminer-docs-connectors pull request #385
Opened 2024-07-22 09:04 UTC by SkylineAjdin

2024-08-06 12:15 UTC, MariekeGO requested changes
Could you adjust this help page so it matches the most recent version of the [connector documentation template](https://docs.dataminer.services/develop/devguide/Connector/ConnectorHelp/Connector_help_template.html)? Specifically, I'm missing the "Version Info", "Product Info", and "System Info" sections here, and the "Installation and configuration" section should be adjusted to a "Configuration" section with "Connections" subtitle and a subtitle for each available connection (which will probably be just the one serial connection). The current "Configuration" subtitle could be changed to "Initialization" instead, or to something more specific (e.g. "Configuration of Virtual Connection").

2024-08-06 13:49 UTC, MariekeGO commented on connector/doc/Beckhoff_KL3202.md
> +The **PositionInfo from BK9000** needs to be configured with a virtual connection to the **PositionInfo** of the right entry of the **Module Table** in the **Beckhoff BK9000** connector. This connect
Where is it that this can be configured? I'm a little concerned that this might not be clear enough to the user right now, so we may still need to add this.

2024-08-06 13:56 UTC, SkylineAjdin commented on connector/doc/Beckhoff_KL3202.md
> +The **PositionInfo from BK9000** needs to be configured with a virtual connection to the **PositionInfo** of the right entry of the **Module Table** in the **Beckhoff BK9000** connector. This connect
Do you mean the Virtual Connection?
Configuration of the Virtual Connection is done on another connector, mentioned there "Beckhoff BK9000", table from that other connector is also mentioned "Module Table". More details on that can be found on help page for Beckhoff BK9000

2024-08-07 06:29 UTC, MariekeGO commented on connector/doc/Beckhoff_KL3202.md
> +The **PositionInfo from BK9000** needs to be configured with a virtual connection to the **PositionInfo** of the right entry of the **Module Table** in the **Beckhoff BK9000** connector. This connect
So is "PositionInfo from BK9000" a parameter in the Beckhoff KL3202 element that needs to be filled in with a "PositionInfo" entry from the "Module Table" of the Beckhoff BK9000 connector? Or should I interpret this differently?

2024-08-07 07:52 UTC, SkylineAjdin commented on connector/doc/Beckhoff_KL3202.md
> +The **PositionInfo from BK9000** needs to be configured with a virtual connection to the **PositionInfo** of the right entry of the **Module Table** in the **Beckhoff BK9000** connector. This connect
Yes, that's correct interpretation.

2024-08-07 08:02 UTC, MariekeGO approved these changes

2024-08-07 08:02 UTC, merged