Tdf manager
SkylineCommunications/dataminer-docs-connectors pull request #457
Opened 2024-09-11 14:45 UTC by tiagopinaskyline

2024-09-13 12:23 UTC, MariekeGO requested changes
As I do not have write access to your PR, I haven't been able to implement any changes directly. Could you take a look at my comments and implement the necessary changes? Also, for future PRs, could you make sure I have write access, for a more efficient immediate review?

2024-09-13 12:23 UTC, MariekeGO commented on connector/toc.yml
> +    topicUid: Connector_help_TDF_EPM_Manager
Could you move this up above TDF GE TBOX, so the alphabetical order is correct?

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +The **TDF EPM Manager** connector is an Experience and Performance Management connector, and as such it is designed to handle large amounts of data from the deployed infrastructures. It manages and m
```suggestion
The **TDF EPM Manager** connector is an Experience and Performance Management connector, and as such it is designed to handle large amounts of data from the deployed infrastructures. It manages and monitors devices across various Equipment Management Systems (EMSs), maintaining relational data and aggregating data that can be viewed through a central front-end interface and the DataMiner Topology app.
```

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +## About
```suggestion
The geographical topology is presented in the TDF EPM Manager and represents a connected entity from top to bottom:

- **Geographical**
  - Zone
  - Department
  - Site
  - Equipment
- **Configuration**
  Allows you to place Visual Overview layouts on a separate chain.
  
## About
```

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +|1.0.0.x    |No       |Yes         |-         |   |
```suggestion
### Version Info

| Range              | Features        | Based on | System Impact |
|--------------------|-----------------|----------|---------------|
| 1.0.0.x [SLC Main] | Initial version | -        | -             |

### System Info

| Range   | DCF Integration | Cassandra Compliant | Linked Components | Exported Components |
|---------|-----------------|---------------------|-------------------|---------------------|
| 1.0.0.x | No              | Yes                 | -                 | -                   |
```

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +    - On the **Configuration** page, change the **Element Manager Type** to Frontend.
```suggestion
    - On the **Configuration** page, change the **Element Manager Type** to *Frontend*.
```

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +1. Create a single **front-end element** and configure it as follows:
```suggestion
When creating the managers manually, follow these steps:

1. Create a single **front-end element** and configure it as follows:
```

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +2. Create as many **back-end** elements as needed.
Could you adjust the numbering of this list item and all items below so that each item starts with "1."? 
See https://docs.dataminer.services/contributing/CTB_Markdown_Syntax.html#lists.

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +    - In **Frontend Registration** table, fill in the DMA ID/Element ID of the front-end element.
Could you add an empty line above the list here and above the list below (line 62). Ideally, a list should always be between blank lines.

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +Once the EPM Manager elements are configured, the only required procedure is for the front-end element to import the following CSV files and initiate the ID assignment process.
```suggestion
Once the EPM Manager elements are configured, the only required procedure is for the front-end element to import the following CSV files and initiate the ID assignment process:
```

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +The front-end element creates structured files with unique IDs per entity for the back-end and collector elements. Additionally, an extra file is generated per collector, containing equipment and sit
```suggestion
## Notes

The front-end element creates structured files with unique IDs per entity for the back-end and collector elements. Additionally, an extra file is generated per collector, containing equipment and site-related information from the Helios DB - inventory with equipment and site metadata for all service types.
```

2024-09-13 12:23 UTC, MariekeGO commented on connector/doc/TDF_EPM_Manager.md
> +- Helios DB-Sites.csv
```suggestion
This file is created based on two other files that are regularly generated by the **TDF Helios Database** connector:

- Helios DB-Equipments.csv
- Helios DB-Sites.csv

```

2024-09-16 11:58 UTC, tiagopinaskyline commented on connector/doc/TDF_EPM_Manager.md
> +2. Create as many **back-end** elements as needed.
Done

2024-09-16 11:58 UTC, tiagopinaskyline commented on connector/doc/TDF_EPM_Manager.md
> +    - In **Frontend Registration** table, fill in the DMA ID/Element ID of the front-end element.
Done

2024-09-16 12:04 UTC, tiagopinaskyline commented on connector/toc.yml
> +    topicUid: Connector_help_TDF_EPM_Manager
Done

2024-09-17 08:56 UTC, MariekeGO approved these changes

2024-09-17 08:56 UTC, merged