Added Peak Communications Sky UK Polarization Switch driver
SkylineCommunications/dataminer-docs-connectors pull request #46
Opened 2023-10-26 09:19 UTC by dariosarkanovic

2023-10-26 12:11 UTC, MariekeGO requested changes

2023-10-26 12:11 UTC, MariekeGO commented on connector/doc/Peak_Communications_Sky_UK_Polarization_Switch.md
> +
The "System Info" table is missing here. Could you still add this? This table contains important information about DCF and Cassandra compatibility. See https://docs.dataminer.services/develop/devguide/Connector/ConnectorHelp/Connector_help_pages.html#about-section.

2023-10-27 08:13 UTC, MariekeGO commented on connector/doc/Peak_Communications_Sky_UK_Polarization_Switch.md
> +
This still needs to be fixed. An example of such a table:
![image](https://github.com/SkylineCommunications/dataminer-docs-connectors/assets/94605575/3e035743-5028-450e-8fbb-fbe64e59527b)

2023-10-27 08:28 UTC, dariosarkanovic commented on connector/doc/Peak_Communications_Sky_UK_Polarization_Switch.md
> +
System Info added.

2023-10-27 08:39 UTC, MariekeGO approved these changes

2023-10-27 08:39 UTC, merged