2wcom mpx 2ds
SkylineCommunications/dataminer-docs-connectors pull request #73
Opened 2023-11-17 10:10 UTC by Guilherme-GR

2023-11-30 14:29 UTC, MariekeGO requested changes

2023-11-30 14:29 UTC, MariekeGO commented on connector/doc/2WCOM_MPX-2ds.md
> +## How to Use
Could you add information on how to use the connector, as instructed under [Connector documentation](https://docs.dataminer.services/develop/devguide/Connector/ConnectorHelp/Connector_help_pages.html#how-to-use-section).

2024-02-16 10:34 UTC, Guilherme-GR commented on connector/doc/2WCOM_MPX-2ds.md
> +## How to Use
Being a small, simple monitoring connector, I just added the only configuration useful for the user to configure.

2024-02-16 10:36 UTC, Guilherme-GR reviewed
requested changes addressed

2024-02-16 13:54 UTC, MariekeGO approved these changes

2024-02-16 13:54 UTC, merged